spring:
  datasource:
    username: AccountTest
    password: 1234567890
    url: jdbc:postgresql://localhost:5432/telegram_bot_tb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
bot:
  name: safety_volkov_bot
  token: 6635776029:AAHlYANQJ_0zW9VBv1nC2uz0jUc0RLHGE5Q